#!/usr/bin/env bash

set -e
[[ "$1" == "--revert" ]] && from=dark || from=light
[[ "$1" == "--revert" ]] && to=light || to=dark

configs=(
    ~/dev/dotfiles/alacritty/local.yml
    ~/dev/dotfiles/git/local
    ~/dev/dotfiles/kitty/local.conf
    ~/dev/dotfiles/tmux/local.conf
    ~/dev/dotfiles/wezterm/local.lua
)

for config in "${configs[@]}"; do
    for commentStr in '--' '#'; do
        [ ! -f "$config" ] && continue

        # Handle lines with theme comment at the end.
        perl -i'' -pe "s/^(\s*+)(?!$commentStr)(.*$commentStr $from theme)/\1$commentStr\2/g" "$config"
        perl -i'' -pe "s/^(\s*+)$commentStr(.*$commentStr $to theme)/\1\2/g" "$config"

        # Handle lines with theme comment in the previous line.
        perl -0777 -i'' -pe "s/(?m)^(\s*$commentStr $from theme\s+)^(?!$commentStr)/\1$commentStr/g" "$config"
        perl -0777 -i'' -pe "s/(?m)^(\s*$commentStr $to theme\s+)^($commentStr)/\1/g" "$config"
    done
done

# [ -f ~/.tmux.conf ] && tmux source-file ~/.tmux.conf
