#!/usr/bin/env bash
FG='\033[37m'
BG0='\033[47m';
BG1='\033[45m';
BG2='\033[46m';
NC='\033[0m'

dir=$(basename "$(pwd)")
declare -A config

case $dir in
  laradock)
    config=( ['container']='workspace' ['params']='-u laradock -w /var/www/laravel')
    ;;

  *)
    config=( ['container']='web' ['params']='')
esac

command=$(printf '%q ' "$@")
wrapperCommand="source ~/.bashrc; $command"

echo -ne   "${BG0}docker compose exec " 
echo -n    ${config[params]} ${config[container]}' '
echo -ne   "${FG}${BG2}bash -ic \"source ~/.bashrc;${BG1} "
echo -n    $command
echo -n    " "
echo -e    "${BG2}\"${NC}\n"

# Word splitting is intentional.
# shellcheck disable=SC2086
docker compose exec ${config[params]} ${config[container]} bash -ic "$wrapperCommand"
