#!/usr/bin/env bash
WHITE_FG='\033[37m'
BLACK_FG='\033[30m';
GREEN_FG='\033[92m';
GRAY_FG='\033[97m';
YELLOW_FG='\033[93m';
WHITE_BG='\033[47m'
BLACK_BG='\033[40m';
GREEN_BG='\033[102m';
GRAY_BG='\033[107m';

NC='\033[0m'

# For custom config, copy the contents of the "else" block below
# to $custom and change to your needs.
custom=~/.config/de-config
if [ -f $custom ]; then
  source $custom
else
  dir=$(basename "$(pwd)")
  declare -A config

  case $dir in
    laradock|laravel)
      config=( ['container']='laradock-workspace-1' ['params']='-u laradock -w /var/www/laravel')
      ;;

    symfony)
      config=( ['container']='laradock-workspace-1' ['params']='-u laradock -w /var/www/symfony')
      ;;

    *)
      config=( ['container']='web' ['params']='')
  esac
fi

command=$(printf '%q ' "$@")
wrapperCommand="source ~/.bashrc; $command"

echo -ne   "docker exec "
echo -n    ${config[params]} ${config[container]}' '
echo -ne   "${YELLOW_FG}"
echo -ne   "bash -ic \"source ~/.bashrc; "
echo -ne   "${GREEN_FG}"
echo -n    $command
echo -e    "${YELLOW_FG}\"${NC}\n"

# Word splitting is intentional.
# shellcheck disable=SC2086
docker exec -it ${config[params]} ${config[container]} bash -ic "$wrapperCommand"
