#!/usr/bin/env bash

GREEN='\033[0;32m';
fail() {
  echo -e "\033[0;31m$1"
  exit 1
}

getCurrent() {
  if kscreen-doctor -o | grep 'DP-1' | grep -q enabled; then
    echo 'main'
  else
    echo 'tv'
  fi
}

setMain() {
  kscreen-doctor \
    output.DP-1.mode.3440x1440@100 \
    output.DP-1.enable \
    output.HDMI-A-1.disable
}

setTv() {
  kscreen-doctor \
    output.DP-1.disable \
    output.HDMI-A-1.mode.3840x2160@60 \
    output.HDMI-A-1.enable \
    output.HDMI-A-1.scale.3
}

if [[ $1 == '' && $(getCurrent) == 'main' ]]; then
  setTv
elif [[ $1 == '' && $(getCurrent) == 'tv' ]]; then
  setMain
elif [[ $1 == 'main' ]]; then
  setMain
elif [[ $1 == 'tv' ]]; then
  setTv
else 
  fail "Unknown display source \"$1\"."
fi
