#!/usr/bin/env php
<?php

$dir = $argv[1];
$dryRun = in_array('--dry-run', $argv);
$verbose = !in_array('--no-verbose', $argv);
$paths = glob("$dir/*");

foreach ($paths as $i => $path) {
    if (!preg_match('/\.jp.?g$/i', $path)) continue;
    if (!($exif = exif_read_data($path))) continue;

    $timezone = trim(`cat /etc/timezone`);
    if (!$timezone) {
        die("Could not get timezone");
    }
    date_default_timezone_set($timezone);

    $exifTime = strtotime($exif['DateTimeOriginal']);
    $fsTime = filemtime($path);

    if (abs($exifTime - $fsTime) < 60) {
        if ($dryRun && $verbose) {
            echo "Will not touch $path\n";
        }
        printProgress($i, count($paths));
        continue;
    }

    $explanation = "(original time) " . date('Y-m-d H:i:s', $exifTime) .
        " !== " . date('Y-m-d H:i:s', $fsTime) . " (modified time)";

    if ($dryRun) {
        echo "Will touch $path because $explanation\n";
    }
    else {
        echo "Touching $path because $explanation\n";
        touch($path, strtotime($exif['DateTimeOriginal']));
    }
    printProgress($i, count($paths));
}

printProgress($i, count($paths));

function printProgress($i, $total)
{
    static $lastReport = time();
    if (time() - $lastReport < 5) {
        return;
    }
    $lastReport = time();

    $progress = ($i + 1) / $total * 100
    |> ceil(...);

    echo "$progress%\n";
}
