#!/usr/bin/env bash

# Delete PVCs
kubectl get pvc --template '{{range $x := .items}}{{$x.metadata.name}}{{"\n"}}{{end}}' | xargs -I{} kubectl delete pvc {}

# Delete PVs
kubectl get pv --template '{{range $x := .items}}{{$x.metadata.name}}{{"\n"}}{{end}}' | xargs -I{} kubectl delete pv {}

# Clear and recreate directories used by PVs
host1=kubernetes-master
host2=kubernetes-node1
host3=kubernetes-node2

if [ "$host1" ] && ping -c 1 -W 0.1 "$host1" >/dev/null; then
  ssh rafal@$host1 -t "sudo find /root -maxdepth 1 -name 'kube-pv*' -exec rm -rf {} +; \
    sudo mkdir /root/kube-pv1; \
    sudo mkdir /root/kube-pv2; \
    sudo mkdir /root/kube-pv3"
fi

if [ "$host2" ] && ping -c 2 -W 0.1 "$host2" >/dev/null; then
  ssh rafal@$host2 -t "sudo find /root -maxdepth 1 -name 'kube-pv*' -exec rm -rf {} +; \
    sudo mkdir /root/kube-pv1; \
    sudo mkdir /root/kube-pv2; \
    sudo mkdir /root/kube-pv3"
fi

if [ "$host3" ] && ping -c 3 -W 0.1 "$host3" >/dev/null; then
  ssh rafal@$host3 -t "sudo find /root -maxdepth 1 -name 'kube-pv*' -exec rm -rf {} +; \
    sudo mkdir /root/kube-pv1; \
    sudo mkdir /root/kube-pv2; \
    sudo mkdir /root/kube-pv3"
fi

# Create PVs
kubectl apply -f ~/Dev/kubernetes-tutorials/stateful-set-basics/volumes.yaml
