#!/usr/bin/env bash

host1=kubernetes-master
host2=kubernetes-node1
host3=kubernetes-node2

if [ "$host1" ] && ping -c 1 -W 0.1 "$host1" > /dev/null; then
    ssh rafal@kubernetes-master -t "sudo sh -c 'rm -r /root/master-pv*/*'; sudo mkdir /root/master-pv1; sudo mkdir /root/master-pv2"
fi

if [ "$host2" ] && ping -c 2 -W 0.1 "$host2" > /dev/null; then
    ssh rafal@kubernetes-node1 -t "sudo sh -c 'rm -r /root/node1-pv*/*'; sudo mkdir /root/node1-pv1; sudo mkdir /root/node1-pv2"
fi

if [ "$host3" ] && ping -c 3 -W 0.1 "$host3" > /dev/null; then
    ssh rafal@kubernetes-node2 -t "sudo sh -c 'rm -r /root/node2-pv*/*'; sudo mkdir /root/node2-pv1; sudo mkdir /root/node2-pv2"
fi
