#!/usr/bin/env sh
perl -pi -e 's/(Lock Session=Meta\+L\\t)Ctrl\+Alt\+L\\t/$1/' ~/.config/kglobalshortcutsrc
perl -pi -e 's/(Activate Window Demanding Attention)=Ctrl\+Alt\+A/$1=none/' ~/.config/kglobalshortcutsrc
perl -pi -e 's/(Expose)=Ctrl\+F9/$1=none/' ~/.config/kglobalshortcutsrc
perl -pi -e 's/(ExposeAll=)Ctrl\+F10\\t/$1/' ~/.config/kglobalshortcutsrc
perl -pi -e 's/(ExposeClass)=Ctrl\+F7/$1=none/' ~/.config/kglobalshortcutsrc
perl -pi -e 's/(ShowDesktopGrid)=Ctrl\+F8/$1=none/' ~/.config/kglobalshortcutsrc
perl -pi -e 's/(Switch to Desktop 1)=Ctrl\+F1/$1=none/' ~/.config/kglobalshortcutsrc
perl -pi -e 's/(Switch to Desktop 2)=Ctrl\+F2/$1=none/' ~/.config/kglobalshortcutsrc
perl -pi -e 's/(Switch to Desktop 3)=Ctrl\+F3/$1=none/' ~/.config/kglobalshortcutsrc
perl -pi -e 's/(Switch to Desktop 4)=Ctrl\+F4/$1=none/' ~/.config/kglobalshortcutsrc
perl -pi -e 's/(Window Minimize=Meta\+PgDown),/$1\\tMeta+H,/' ~/.config/kglobalshortcutsrc
perl -pi -e 's/(Window Operations Menu)=Alt\+F3/$1=none/' ~/.config/kglobalshortcutsrc
perl -pi -e 's/(FullScreenScreenShot=Shift\+Print,)/FullScreenScreenShot=Print,/' ~/.config/kglobalshortcutsrc
perl -pi -e 's/_launch=Print,Print,Spectacle/_launch=Shift+Print,Print,Spectacle/' ~/.config/kglobalshortcutsrc
