#!/usr/bin/env bash

sed=$(which gsed >> /dev/null && echo -n 'gsed' || echo -n 'sed')

$sed -i 's/^\( *-.*# dark theme\)/#\1/' ~/Dev/dotfiles/alacritty/local.yml &&
        $sed -i 's/^# *\(-.*# light theme\)/  \1/' ~/Dev/dotfiles/alacritty/local.yml