#!/usr/bin/env bash
# shellcheck disable=SC2015

step-header() {
  echo -e '\e[93m\e[1m------------------------------'
  echo "$1"
  echo -e '------------------------------\e[0m\n'
}

fail() {
    echo "$1"
    exit 1
}

if [ "$USER" = root ]; then
    # We need $USER to be our regular user, not root, so this script shouldn't be run with sudo.
    echo "Please run this script without sudo and as a regular user. Sudo will be added where necessary."
    exit 1
fi

step-header 'SSH'
if [ ! -f ~/.ssh/id_ed25519.pub ]; then
    # shellcheck disable=SC2034
    ssh-keygen -t ed25519 &&
        cat ~/.ssh/id_ed25519.pub &&
        read -rp "Press Enter after saving the SSH key to Github" confirm ||
        fail 'SSH error'
fi

if [ ! -f ~/.ssh/config ]; then
    echo 'AddKeysToAgent yes' > ~/.ssh/config
fi

step-header 'Global settings'
sudo timedatectl set-local-rtc 1 ||
    fail 'Settings error'

step-header "Pamac packages (early)"
sudo pamac install --no-confirm \
    keepassxc \
    nextcloud \
    yay ||
    fail "Pamac installation (early) error"

step-header "FreeFileSync"

if [ ! -f /opt/freefilesync/FreeFileSync ]; then
    yay -S --answerdiff None --answerclean None --removemake \
        freefilesync-bin ||
        fail 'FreeFileSync installation error'
fi

step-header 'Pacman packages'
sudo pacman -Syu --noconfirm \
    bat \
    composer \
    curl \
    libxcrypt-compat ||
    fail 'Pamac installation error'

step-header 'Pamac packages'
sudo pamac install --no-confirm \
    ack \
    audacity \
    baobab \
    base-devel \
    docker \
    exa \
    freerdp \
    gimp \
    gnome-keyring \
    helm \
    htop \
    iotop \
    jq \
    jre-openjdk \
    keepassxc \
    kitty \
    libvncserver \
    lynx \
    meld \
    net-tools \
    nodejs \
    npm \
    php \
    php-gd \
    thunar \
    tmux \
    tree \
    tumbler \
    vim \
    xclip \
    xdotool \
    xfce4-terminal \
    yay \
    virtualbox \
    vivaldi ||
    fail 'Pamac installation error'

step-header 'Yay packages'

if ! which jetbrains-toolbox; then
    yay -S --answerdiff None --answerclean None --removemake \
        jetbrains-toolbox ||
        fail 'JetBrains Toolbox installation error'
fi

if ! which postman; then
    yay -S --answerdiff None --answerclean None --removemake \
        postman-bin ||
        fail 'Postman installation error'
fi

step-header 'Flatpak packages'
sudo flatpak install -y org.remmina.Remmina &&
    sudo flatpak install -y com.spotify.Client ||
    fail 'Flatpak installation error'

step-header 'Snap packages'
if [ ! -s /snap ]; then
    sudo ln -s /var/lib/snapd/snap /snap ||
    fail "Snap symlink error"
fi;

sudo snap install code --classic &&
    sudo snap install dbeaver-ce &&
    sudo snap install skype &&
    sudo snap install redis-desktop-manager ||
    fail 'Snap installation error'

step-header 'Docker'

sudo systemctl enable docker ||
    fail 'Docker service enabling error'

sudo usermod -aG docker "$USER" ||
    fail 'Usermod error'

step-header 'Docker compose'
if ! which docker-compose; then
    sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    sudo chmod +x /usr/local/bin/docker-compose ||
    fail 'Docker Compose error'
fi

step-header 'PHP'
sudo sed -i 's/;extension=exif/extension=exif/' /etc/php/php.ini &&
    sudo sed -i 's/;extension=gd/extension=gd/' /etc/php/php.ini &&
    sudo sed -i 's/;extension=soap/extension=soap/' /etc/php/php.ini ||
    fail 'PHP extension enabling error'

step-header 'Bin folder'
if [ ! -d ~/bin ]; then
    cd ~ &&
        git clone git@github.com:rafalglowacz/bin.git ||
        fail 'Bin error'
fi

step-header 'SSH agent finder'
if [ ! -d ~/bin/ssh-find-agent ]; then
    cd ~/bin &&
    git clone https://github.com/wwalker/ssh-find-agent.git ||
    fail 'SSH finder error'
fi

step-header 'Dotfiles'
[ ! -d ~/Dev ] && mkdir ~/Dev

if [ ! -d ~/Dev/dotfiles ]; then
    cd ~/Dev &&
        git clone git@github.com:rafalglowacz/dotfiles.git ||
        fail 'Dotfiles error'
fi

sudo chsh -s "$(which zsh)" "$USER" ||
    fail 'Default shell change error'

step-header 'Symlinks'
[ ! -d ~/.config/kitty ] && mkdir ~/.config/kitty

rm -f ~/.ackrc &&
    rm -f ~/.gitconfig &&
    rm -f ~/.config/kitty/kitty.conf &&
    rm -f ~/.config/kitty/startup &&
    rm -f ~/.tmux.conf &&
    rm -f ~/.zshrc &&
    ln -s ~/Dev/dotfiles/ackrc.ackrc ~/.ackrc &&
    ln -s ~/Dev/dotfiles/gitconfig ~/.gitconfig &&
    ln -s ~/Dev/dotfiles/kitty.conf ~/.config/kitty/kitty.conf &&
    ln -s ~/Dev/dotfiles/kitty-startup ~/.config/kitty/startup &&
    ln -s ~/Dev/dotfiles/tmux.conf ~/.tmux.conf &&
    ln -s ~/Dev/dotfiles/manjaro-2022.zshrc ~/.zshrc ||
    fail 'Symlinks error'

step-header 'FZF'
if [ ! -d ~/.fzf ]; then
    git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf &&
        ~/.fzf/install --key-bindings --completion --update-rc ||
        fail 'FZF error'
fi

step-header 'Tmux themes'
if [ ! -d ~/Documents/tmux-themepack ]; then
    cd ~/Documents &&
        git clone https://github.com/jimeh/tmux-themepack.git ||
        fail 'Tmux themepack error'
fi

step-header 'Grub'
if ! grep -q 'GRUB_TIMEOUT=1' /etc/default/grub; then
    sudo sed -i 's/GRUB_TIMEOUT=./GRUB_TIMEOUT=1/' /etc/default/grub &&
    sudo update-grub ||
    fail 'Grub error'
fi

step-header 'NPM global packages'
if ! which tldr; then
    sudo npm install -g tldr
fi

if ! which git-trim; then
    sudo npm install -g git-trim
fi

echo -e '\n\e[32m\e[1m------------------------------'
echo 'Done'
echo -e '------------------------------\e[0m'
