#!/usr/bin/env bash

source $(dirname $0)/_functions

userHost=$1

if [ -z "$1" ]; then
    fail "Usage: $(basename $0) user@hostname"
fi

step-header "Color prompt"
ssh $userHost sed -i 's/#force_color_prompt/force_color_prompt/' /root/.bashrc ||
    fail "Forcing color prompt failed"

step-header "Update"
ssh $userHost apt update || 
    fail "Update failed"

step-header "Upgrade"
# -t because we might need to answer a prompt about newer versions of configuration
# files. I didn't find a way to assume one of the anwers.
ssh -t $userHost apt upgrade -y ||
    fail "Upgrade failed"

