#!/usr/bin/env bash
# shellcheck disable=SC2164

GREEN='\033[0;32m';
YELLOW='\033[0;33m';
RED='\033[0;31m';
NC='\033[0m'

unpushed=()

checkPath() {
  local path=$1
  cd "$path"
  status=$(git status)
  if ! (echo "$status" | grep -q 'nothing to commit, working tree clean'); then
    echo -e "$YELLOW------------------------------"
    pwd
    echo -e "------------------------------$NC\n"
    git status # TODO: find out how to display $status without losing colors
    echo
  else
    echo -e "${GREEN}✓$NC clean: $(pwd | sed 's/\n//')"
    if [[ $(git log @{u}..) ]]; then 
      echo -e "  ${YELLOW}! Has unpushed changes.$NC"
      unpushed+=($path)
    fi
  fi
}

fail() {
    echo "$1"
    exit 1
}

containedIn () {
  local e match="$1"
  shift
  for e; do [[ "$e" == "$match" ]] && return 0; done
  return 1
}

if [ -f ~/.vcs-exclusions ]; then
  source ~/.vcs-exclusions;
else
  except=(
    "laradock"
    "laravel"
  )
fi

for dir in ~/Dev/*; do
  if [ ! -d "$dir" ]; then continue; fi
  if [ ! -d "$dir/.git" ]; then continue; fi
  cd "$dir";
  if (($(git remote -v | wc -l) == 0)); then continue; fi
  if containedIn "$(basename "$dir")" "${except[@]}"; then continue; fi

  checkPath "$dir"
done

checkPath ~/bin
[ -d ~/bin2 ] && checkPath ~/bin2
[ -d ~/Documents/Logseq ] && checkPath ~/Documents/Logseq
[ -d ~/Documents/LogSeq\ -\ Home ] && checkPath ~/Documents/LogSeq\ -\ Home
[ -d ~/Documents/LogSeq\ -\ Work ] && checkPath ~/Documents/LogSeq\ -\ Work

[ -d ~/.config/JetBrains ] && JETBRAINS_DIR=~/.config/JetBrains/ || JETBRAINS_DIR=~/Library/Application\ Support/JetBrains

if [ -d "$JETBRAINS_DIR" ]; then
  cd "$JETBRAINS_DIR" || fail "JetBrains config directory doesn't exist"
  stormDir=$(ls -1d PhpStorm* | tail -n 1)
  checkPath "$JETBRAINS_DIR/$stormDir/keymaps"
fi

stillUnpushed=()

if [[ ${#unpushed[@]} > 0 ]]; then
  echo
  echo "There's committed but unpushed changes in ${unpushed[@]}."
  read -p "Do you want to push them? (Y/n):" confirm
  if [[ ${confirm:0:1} != 'n' ]]; then
    for path in ${unpushed[@]}; do
      echo -e "${YELLOW}$path${NC}\n"
      cd $path
      git push $maybeForcePush
      if [ "$?" -eq 1 ]; then stillUnpushed+=($path); fi
    done
  fi
fi

if [[ ${#stillUnpushed[@]} > 0 ]]; then
  echo
  echo "Pushes were rejected for ${unpushed[@]}."
  read -p "Do you want to force-push them? (y/N):" confirm
  if [[ ${confirm:0:1} == 'y' ]]; then
    for path in ${unpushed[@]}; do
      echo -e "${RED}$path${NC}\n"
      cd $path
      git push --force
    done
  else
    echo -e "${YELLOW}Unpushed changes left behind!${NC}"
  fi
fi

echo
# shellcheck disable=SC2034
read -rp "$(date +%H:%M) Press RETURN" confirm

if [[ $1 == '-r' ]]; then
  reboot
else
  shutdown now
fi
