#!/usr/bin/env bash
# shellcheck disable=SC2164

GREEN='\033[0;32m';
YELLOW='\033[0;33m';
NC='\033[0m'

checkPath() {
  local path=$1
  cd "$path"
  status=$(git -c color.ui=always pull 2>&1)
  if ! (echo "$status" | grep -q 'Already up to date.'); then
    echo -e "$YELLOW------------------------------"
    pwd
    echo -e "------------------------------$NC\n"
    echo "$status"
    echo
  else
    echo -e "${GREEN}✓$NC up to date: $(pwd | sed 's/\n//')"
  fi
}

fail() {
    echo "$1"
    exit 1
}

containedIn () {
  local e match="$1"
  shift
  for e; do [[ "$e" == "$match" ]] && return 0; done
  return 1
}

if [ -f ~/.vcs-exclusions ]; then
  source ~/.vcs-exclusions;
else
  except=(
    "laradock"
    "laravel"
  )
fi

for dir in ~/dev/*; do
  if [ ! -d "$dir" ]; then continue; fi
  if [ ! -d "$dir/.git" ]; then continue; fi
  cd "$dir";
  if (($(git remote -v | wc -l) == 0)); then continue; fi
  if containedIn "$(basename "$dir")" "${except[@]}"; then continue; fi

  checkPath "$dir"
done

checkPath ~/bin
[ -d ~/bin2 ] && checkPath ~/bin2
[ -d ~/dev/arduino/Mode100 ] && checkPath ~/dev/arduino/Model100

[ -d ~/.config/JetBrains ] && JETBRAINS_DIR=~/.config/JetBrains/ || JETBRAINS_DIR=~/Library/Application\ Support/JetBrains
[ -d ~/.config/Google ] && GOOGLE_DIR=~/.config/Google || GOOGLE_DIR=~/Library/Application\ Support/Google

if [ -d "$JETBRAINS_DIR" ]; then
  cd "$JETBRAINS_DIR"
  stormDir=$(ls -1d PhpStorm* 2>/dev/null | grep -v backup | tail -n 1)
  roverDir=$(ls -1d RustRover* 2>/dev/null | grep -v backup | tail -n 1)
  webStormDir=$(ls -1d WebStorm* 2>/dev/null | grep -v backup | tail -n 1)

  if [ -n "$stormDir" ]; then
    checkPath "$JETBRAINS_DIR/$stormDir"
  fi
  if [ -n "$roverDir" ]; then
    checkPath "$JETBRAINS_DIR/$roverDir"
  fi
  if [ -n "$webStormDir" ]; then
    checkPath "$JETBRAINS_DIR/$webStormDir"
  fi
fi

if [ -d "$GOOGLE_DIR" ]; then
  cd "$GOOGLE_DIR"
  androidStudioDir=$(ls -1d AndroidStudio* 2>/dev/null | grep -v backup | tail -n 1)

  if [ -n "$androidStudioDir" ]; then
    checkPath "$GOOGLE_DIR/$androidStudioDir"
  fi
fi
