#!/usr/bin/env bash
# shellcheck disable=SC2164

GREEN='\033[0;32m';
YELLOW='\033[0;33m';
NC='\033[0m'

checkPath() {
  local path=$1
  cd "$path"
  status=$(git pull 2>&1)
  if ! (echo "$status" | grep -q 'Already up to date.'); then
    echo -e "$YELLOW------------------------------"
    pwd
    echo -e "------------------------------$NC\n"
    echo "$status" # TODO: find out how to display $status without losing colors
    echo
  else
    echo -e "${GREEN}✓$NC up to date: $(pwd | sed 's/\n//')"
  fi
}

fail() {
    echo "$1"
    exit 1
}

containedIn () {
  local e match="$1"
  shift
  for e; do [[ "$e" == "$match" ]] && return 0; done
  return 1
}

if [ -f ~/.vcs-exclusions ]; then
  source ~/.vcs-exclusions;
else
  except=(
    "laradock"
    "laravel"
  )
fi

for dir in ~/Dev/*; do
  if [ ! -d "$dir" ]; then continue; fi
  if [ ! -d "$dir/.git" ]; then continue; fi
  cd "$dir";
  if (($(git remote -v | wc -l) == 0)); then continue; fi
  if containedIn "$(basename "$dir")" "${except[@]}"; then continue; fi

  checkPath "$dir"
done

checkPath ~/bin
[ -d ~/bin2 ] && checkPath ~/bin2
[ -d ~/Documents/Logseq ] && checkPath ~/Documents/Logseq

[ -d ~/.config/JetBrains ] && JETBRAINS_DIR=~/.config/JetBrains/ || JETBRAINS_DIR=~/Library/Application\ Support/JetBrains

if [ -d "$JETBRAINS_DIR" ]; then
  cd "$JETBRAINS_DIR" || fail "JetBrains config directory doesn't exist"
  stormDir=$(ls -1d PhpStorm* | tail -n 1)
  checkPath "$JETBRAINS_DIR/$stormDir/keymaps"
fi

