#!/usr/bin/env php
<?php

// Get the first argument (format: path/to/file.php:lineNumber)
$input = $argv[1] ?? '';

// Split the path and line number
/**
 * @var string $filePath
 * @var int $lineNumber
 */
[$filePath, $lineNumber] = array_pad(explode(':', $input, 2), 2, null);

// Read the file
/** @var list<string> $lines */
$lines = file($filePath, FILE_IGNORE_NEW_LINES);

// Find the test method name at or before the specified line
$testMethod = null;
for ($i = $lineNumber - 1; $i >= 0; $i--) {
    if (preg_match('/^\s*(?:public|protected|private)?\s*function\s+(\w+)/', $lines[$i], $matches)) {
        $testMethod = $matches[1];
        break;
    }
}

$cmd = "uniexec vendor/bin/phpunit $filePath";

if ($testMethod) {
    $cmd .= " --filter $testMethod";
}

passthru($cmd);
