#!/usr/bin/env bash

fail() {
    echo "$1"
    exit 1
}

tmux kill-server
cd ~/Dev/laradock || fail "~Dev/laradock doesn't exist"

if ! docker-compose ps | grep -q Up; then
    docker-compose start
else
    # If we had to start our services then that provided a sufficient delay.
    sleep 1
fi

tmux new-session -d -s Laradock
tmux send-keys ws Enter 'cd /var/www/laravel' Enter C-l 
tmux send-keys 'ls -lh' Enter
# tmux send-keys gs Enter

tmux split-window -h
tmux send-keys ws Enter 'cd /var/www/laravel/storage/logs' Enter
#tmux send-keys 'TODAY_LOG=laravel-$(date +$F).log' Enter
tmux send-keys 'TODAY_LOG=laravel.log' Enter
tmux send-keys 'if [[ ! -f $TODAY_LOG ]]; then touch $TODAY_LOG; chmod 777 $TODAY_LOG; fi' Enter
tmux send-keys 'tail -n 1000 -f $TODAY_LOG' Enter
tmux select-pane -t 0

tmux new-window
tmux send-keys 'cd ~/Dev/laradock' Enter C-l

tmux select-window -t 2

tmux attach -t Laradock