#!/usr/bin/env bash

if [ "$USER" = root ]; then
    echo "Please run this script without sudo and as a regular user. Sudo will be added where necessary."
    exit 1
fi

if [ ! -f ~/.ssh/id_ed25519.pub ]; then
    # shellcheck disable=SC2034
    ssh-keygen -t ed25519 &&
        cat ~/.ssh/id_ed25519.pub &&
        read -rp "Press Enter after saving the SSH key to Github" confirm ||
        (echo 'SSH error' && exit 1)
fi

timedatectl set-local-rtc 1 &&
    sudo apt install -y meld git vim gnome-tweaks dconf-editor xdotool php-cli keepassxc zsh tmux docker.io curl &&
    sudo snap install spotify &&
    sudo snap install skype &&
    sudo usermod -aG docker "$USER" ||
    (echo 'Installation error' && exit 1)

if [ ! -d ~/bin ]; then
    cd ~ &&
        git clone git@github.com:rafalglowacz/bin.git ||
        (echo 'Bin error' && exit 1)
fi

if [ ! -d ~/bin/ssh-find-agent ]; then
    cd ~/bin &&
    git clone git@github.com:wwalker/ssh-find-agent.git ||
    (echo 'SSH finder error' && exit 1)
fi

~/bin/keybinds-set 2>&1 | grep -v 'No such schema'

[ ! -d ~/Dev ] && mkdir ~/Dev

if [ ! -d ~/Dev/dotfiles ]; then
    cd ~/Dev &&
        git clone git@github.com:rafalglowacz/dotfiles.git ||
        (echo 'Dotfiles error' && exit 1)
fi

if [ ! -d ~/.oh-my-zsh ]; then
    sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" ||
    (echo 'OMZ error' && exit 1)
fi

if [ ! -d ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions ]; then
    git clone https://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions ||
    echo 'ZSH autosuggestions error' && exit 1
fi

rm ~/.zshrc &&
    rm ~/.tmux.conf &&
    rm ~/.ackrc &&
    rm ~/.gitconfig &&
    ln -s ~/Dev/dotfiles/manjaro-omz.zshrc ~/.zshrc &&
    ln -s ~/Dev/dotfiles/tmux.conf ~/.tmux.conf &&
    ln -s ~/Dev/dotfiles/ackrc.ackrc ~/.ackrc &&
    ln -s ~/Dev/dotfiles/gitconfig ~/.gitconfig ||
    (echo 'Symlinks error' && exit 1)

if [ ! -d ~/.fzf ]; then
    git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf &&
        ~/.fzf/install ||
        (echo 'FZF error' && exit 1)
fi

if [ ! -d ~/Documents/tmux-themepack ]; then
    cd ~/Documents &&
        git clone git@github.com:jimeh/tmux-themepack.git ||
        (echo 'Tmux themepack error' && exit 1)
fi

echo 'Done!'
